### ISSUE TITLE
branding by URL

### ISSUE THREAD

**Issue by patrickbenkoetter** [tonioo/modoboa#493]
Modoboa's Webinterface should support branding by URL. If someone would call modoboa via http://mail.example.com it should use mail.example.com branding and limit the view to the domain example.com and its alias domains.

**Comment by fernandoscheffel** [comment]
I have two subdomins with the respective conf files in the sites-available and sites-enabled (symlink) folder.

I tryied to add the kunago solution in the server blocks but doesnt work. The logo.png works but stay the same logo in my two subdomains.

**Comment by bossey1** [comment]
> Of course. It is quite simple. This is what I am using to change a modoboa default logo based on a hostname:
> 
> ```nginx
> server {
> ...
>   location /media/logo.png {
>     alias /var/www/modoboa_mail/modoboa_mail/media/logo-$host.png;
>     try_files "" /sitestatic/css/modoboa.png;
>   }
> }
> ```
> 
> You need to add this to the "server" directive and name your logos like this: logo-domain.com.png, logo-domain2.com.png, etc. In case the logo for a domain is missing, the default logo is used instead.
> 
> This can be adapted in any way to suit your needs.

So is this set in autoconfig.domain.com or per each domain seperately such as mail.1stdomain.com mail.2nddomain.com etc?

**Comment by jaysenjohnson** [comment]
Hello,

I know this issue is a little old but I am trying to implement this and it is also not working for me.  I added the above lines to my nginx server block as described.  I had to create the directory structure "/var/www/modoboa_mail/modoboa_mail/media/" as it did not exist on my server.  

I uploaded my logo to the newly created directory and named it logo-mail.domain.com.png replacing domain.com with my actual domain.  I restarted nginx to re-read the config but still the default logo shows.  I cleared cache and even tried incognito mode with no success. 

My question is regarding the location line in the above code.  I am assuming "/media" means /srv/modoboa/instance/media/ ?  I looked in that directory and there is no logo.png inside there.

What about file permissions?  I uploaded my logo to /var/www/modoboa_mail/modoboa_mail/media/ directory. Do the permissions on the logo file need to be set to the modoboa user or the nginx webserver user?

Just need a little extra clarification on how to implement this. 

Thank You

**Comment by fernandoscheffel** [comment]
Hi jaysenjohnson,

You need just create the folder. You can specify any name that you want.

alias /var/www/modoboa_mail/modoboa_mail/media/logo-$host.png;

if doesnt exist the folder modoboa_mail/modoboa_mail, you have two choises, create the folder or specify a different folder name that exists and put the logo file there.

**Comment by jaysenjohnson** [comment]
Hello,

I have created the folder as described and kept the same names.  Logo is uploaded and named correctly also as described.  I also put the lines of code in my nginx config and restarted nginx but it still doesn't seem to work.  

As far as permissions, 777 isn't something I recommend or use.  The world should not need full permissions to make this work.  My question asked if the folders and logo files needed to be owned by modoboa user or webserver user?  

For the custom logo setting in settings.py.  Yes, I was changing the logo that way and that works. But that only changes the logo globally for all domains and uses a single logo.  The goal is to use different logos per domain to match each client that we host for.  That is what is not working.  It was my understanding that this could be accomplished using the method user "kunago" explained above.  It seems pretty straight-forward to implement but I am clearly missing something.  

Thank You
