### ISSUE TITLE
Create alias with tag (+) in recipient address with internal domain

### ISSUE THREAD

**Issue by harobed** [tonioo/modoboa#713]
It's impossible to create new alias with tag in recipient address.

Example : 

* I've contact@example.com mailbox
* I would like to create foobar@example.com alias with contact+test@example.com recipient

I've this error « Local recipient contact+test@example.com not found ».

Solution proposition : 

* use Alias.extmboxes to record this email address with tag

Do you see other solution ?

**Comment by tonioo** [comment]
This fix could indeed work but it requires a parsing of the email address to detect the delimiter (+) :
* Parse the address
* If there a delimiter character in the local part, remove everything until we found a @ character
* With the remaining address (so contact@example.com) in the previous example, check if it exists locally
* Create the alias using the extmboxes field

Is it corresponding to your intial idea ?

**Comment by harobed** [comment]
Ok, I'm going to implement that.

**Comment by tonioo** [comment]
Great news :)

By the way, I'm currently splitting modoboa applications (I'm almost done with 1.3.0) so the modoboa repository now contains only core files.

Since I consider your need as a feature, I think you should implement it inside the new repository which contains the admin console code: https://github.com/modoboa/modoboa-admin

What do you think ?

**Comment by harobed** [comment]
First, I'm going to fix it in stable version 1.2.1, next I'll implement it to 1.3.0.

**Comment by tonioo** [comment]
Ok, so the 1.2.x branch is the one you're looking for ;)

Anyway, many thanks for you time!
