### ISSUE TITLE
cant set resourcen of from reseller createt domain admin 

### ISSUE THREAD

**Issue by blendi-93** [tonioo/modoboa#859]
os: debian 8
modoboa 1.4.5
mysql Ver 14.14 Distrib 5.5.47
installed installer, anything default (passwords changed)

i have two users:
admin: superadmin
reseller1: reseller

if i create an domain admin with the reseller account i cant change the Resources (mailboxes, mailbox aliases). I cant change it as reseller nor as admin.
i get "Not enough resources"

if i create the domainadmin with my superadmin i can change resources with superadmin.

**Comment by tonioo** [comment]
If you haven't changed the default parameters, you reseller was created with all resources to 0 so you need to update them as super administrator.
One other thing to know: when a reseller creates a domain administrator and gives him resources, he will use his own pool of resources. 

Example 1: R1 can still create 3 mailboxes and allows DA1 to create 2 mailboxes, it works. After this operation, R1 will have 1 mailbox left.

Example 2: R1 can still create 3 mailboxes and allows DA1 to create 5 mailboxes, it does not work because R1 does not have enough resource.

Is it clearer now ?

**Comment by blendi-93** [comment]
ok, in modoboa settings tab i setup limits: anyting to -1 (unlimited)
this setting was also used as new default but instead giving me unblimited resources for this user i got 0.

if i change the limits for the reseller (-1 => 999) i finaly can give resources to my domainadmins.

domains -1 works
mailboxes -1 doesnt work.

**Comment by tonioo** [comment]
@blendi-93 what kind of user are you using to define limits ? (what'is role ?)

**Comment by blendi-93** [comment]
i used the admin to create a reseller and createt a domain admin with reseller.
admin => reseller => domainadmin.
